name: Database Migrations

on:
  push:
    branches:
      - main
    paths:
      - ci_finished.txt

jobs:
  migrate:
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }} # Endpoint do RDS
      DB_PORT: 5432
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run migrations
        run: npx prisma migrate deploy
