name: Database Migrations

on:
  push:
    branches:
      - main
    paths:
      - ci_finished.txt

jobs:
  migrate:
    name: 'Run Migrations'
    runs-on: ubuntu-latest
    environment: Development
    needs: [run-terraform]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        run: |
          mkdir -p ~/.aws
          echo "[lab-academy]
          aws_access_key_id=${{ vars.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key=${{ vars.AWS_SECRET_ACCESS_KEY }}
          aws_session_token=${{ vars.AWS_SESSION_TOKEN }}" > ~/.aws/credentials
      
      - name: Get RDS Endpoint from SSM
        id: get-endpoint
        run: |
          echo "DB_HOST=$(aws ssm get-parameter --name '/dev/database/endpoint' --query 'Parameter.Value' --output text)" >> $GITHUB_ENV


      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run migrations
        env:
          # DB_HOST: ${{ env.DB_HOST }} # Endpoint do RDS
          # DB_PORT: 5432
          # DB_NAME: ${{ vars.DB_NAME }}
          # DB_USER: ${{ vars.DB_USER }}
          # DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DATABASE_URL: "postgresql://${{ vars.DB_USER }:${{ secrets.DB_PASSWORD }}@${{ env.DB_HOST }}/${{ vars.DB_NAME }}"
        run: npx prisma migrate deploy
